# Generated by Django 5.0.2 on 2024-03-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_lang_course_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lang',
            new_name='Language',
        ),
    ]
