# Generated by Django 5.0.2 on 2024-04-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_usercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time_duration',
            field=models.FloatField(null=True),
        ),
    ]
