# Generated by Django 5.0.2 on 2024-05-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_feedback_video_video_description_alter_video_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='course_slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
    ]
