# Generated by Django 5.0.2 on 2024-04-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_description',
            field=models.TextField(default=False),
        ),
    ]
