# Generated by Django 5.0.2 on 2024-04-27 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_video_slug_alter_video_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
    ]
