# Generated by Django 5.0.2 on 2024-05-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_feedback_course_slug_feedback_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
