# Generated by Django 5.0.2 on 2024-04-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_video_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
