# Generated by Django 5.0.2 on 2024-04-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rating', models.DecimalField(choices=[(5, '5 stars'), (4.5, '4 and a half stars'), (4, '4 stars'), (3.5, '3 and a half stars'), (3, '3 stars'), (2.5, '2 and a half stars'), (2, '2 stars'), (1.5, '1 and a half stars'), (1, '1 star'), (0.5, 'half star')], decimal_places=1, max_digits=2)),
            ],
        ),
    ]
