# Generated by Django 5.0.2 on 2024-04-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
