name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files for debugging
      run: |
        ls -al
        ls -al my_venv  # Check the contents of my_venv directory

    - name: Set up Python and create virtual environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Create and activate virtual environment
      run: |
        python -m venv my_venv
        source my_venv/bin/activate
        pip install -r requirements.txt  # Ensure the correct path to requirements.txt

    - name: Build Docker image
      run: |
        docker build -t elearning_app -f Dockerfile .  # Ensure the correct path to Dockerfile

    - name: Push Docker image to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag elearning_app $DOCKER_USERNAME/elearning_app:latest
        docker push $DOCKER_USERNAME/elearning_app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to server
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker pull $DOCKER_USERNAME/elearning_app:latest
        docker run -d -p 8000:8000 $DOCKER_USERNAME/elearning_app:latest
